apiVersion: v1
kind: Secret
metadata:
  name: secret-cj
  namespace: my-app
stringData:
  AWS_SECRET_ACCESS_KEY: "SECRET_ACCESS_KEY"
  AWS_ACCESS_KEY_ID: "ACCESS_KEY_ID"
  AWS_ACCOUNT: "ACCOUNT_ID"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: confmap-cj
  namespace: my-app
data:
  AWS_REGION: ${AWS_REGION}
  DOCKER_SECRET_NAME: secret-app
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
  namespace: my-app
spec:
  schedule: "0 */10 * * *"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: usercj
          containers:
          - name: ecr-registry-helper
            image: odaniait/aws-kubectl:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: secret-cj
              - configMapRef:
                  name: confmap-cj
            command:
              - /bin/sh
              - -c
              - |-
                ECR_TOKEN=`aws ecr get-login-password --region ${AWS_REGION}`
                kubectl delete secret --ignore-not-found secret-app -n my-app
                kubectl create secret docker-registry secret-app \
                --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com \
                --docker-username=AWS \
                --docker-password="${ECR_TOKEN}" \
                --namespace=my-app
                echo "Secret was successfully updated at $(date)"
          restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: usercj
  namespace: my-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-app
  name: role-full-access-to-secrets
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["regcred"]
  verbs: ["delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: health-check-role-binding
  namespace: my-app
subjects:
- kind: ServiceAccount
  name: usercj
  namespace: my-app
  apiGroup: ""
roleRef:
  kind: Role
  name: role-full-access-to-secrets
  apiGroup: ""
---
